# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'length_cali_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 323)
        self.lengthTable = LengthTable(Dialog)
        self.lengthTable.setGeometry(QtCore.QRect(20, 20, 251, 251))
        self.lengthTable.setObjectName("lengthTable")
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setGeometry(QtCore.QRect(290, 280, 331, 31))
        self.OK.setIconSize(QtCore.QSize(30, 30))
        self.OK.setObjectName("OK")
        self.calibration_length = QtWidgets.QPushButton(Dialog)
        self.calibration_length.setGeometry(QtCore.QRect(20, 280, 111, 31))
        self.calibration_length.setIconSize(QtCore.QSize(30, 30))
        self.calibration_length.setObjectName("calibration_length")
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(140, 280, 131, 31))
        self.deleteButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton.setObjectName("deleteButton")
        self.len_info = LenCaliViewer(Dialog)
        self.len_info.setGeometry(QtCore.QRect(300, 20, 311, 249))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.len_info.sizePolicy().hasHeightForWidth())
        self.len_info.setSizePolicy(sizePolicy)
        self.len_info.setObjectName("len_info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OK.setText(_translate("Dialog", "OK"))
        self.calibration_length.setText(_translate("Dialog", "Add"))
        self.deleteButton.setText(_translate("Dialog", "Delete"))
        self.len_info.setText(_translate("Dialog", "len_info"))
from widgets import LenCaliViewer, LengthTable
import res_rc
